---

name: re-build-test

on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      ARTIFACT_ID:
        value: ${{ jobs.build.outputs.ARTIFACT_ID }}

      BUILD_VERSION:
        value: ${{ jobs.build.outputs.BUILD_VERSION }}

      WORKFLOW_RUN_ID:
        value: ${{ jobs.build.outputs.WORKFLOW_RUN_ID }}

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      ARTIFACT_ID: ${{ steps.set-artifact-id.outputs.ARTIFACT_ID }}
      BUILD_VERSION: ${{ steps.set-build-version.outputs.BUILD_VERSION }}
      WORKFLOW_RUN_ID: ${{ steps.set-workflow-runid.outputs.WORKFLOW_RUN_ID }}

    strategy:
      fail-fast: false
      matrix:
        python: ['3.14.x']

    steps:

    - name: Checkout source code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: ${{ matrix.python }}

    - name: Make build
      run: make build

    # set and get build version
    - name: Set Build Version
      id: set-build-version
      run: |
        echo "BUILD_VERSION=$(python src/*/run.py --version | head -1 | awk '{print $3}')" >> "$GITHUB_OUTPUT"

    - name: Get Build Version
      id: get-build-version
      run: |
        echo "Build Version: ${{ steps.set-build-version.outputs.BUILD_VERSION }}"

    # set and get artifacts
    - name: Upload distributions
      id: upload-distributions
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
      with:
        name: distributions-${{ matrix.python }}
        path: dist/
        if-no-files-found: error
        retention-days: 3
        overwrite: true
        compression-level: 6

    - name: Set Artifact ID
      id: set-artifact-id
      run: |
        echo "ARTIFACT_ID=${{ steps.upload-distributions.outputs.artifact-id }}" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        # output artifact id
        echo "ARTIFACT_ID: ${{ steps.upload-distributions.outputs.artifact-id }}"

    - name: Set Workflow Run ID
      id: set-workflow-runid
      run: |
        echo "WORKFLOW_RUN_ID=${{ github.run_id }}" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        # output workflow run-id
        echo "Workflow Run ID: ${{ github.run_id }}"

  test:

    permissions:
      contents: write
      pull-requests: write

    needs: build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: ['3.14.x']

    steps:

    - name: Checkout source code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: ${{ matrix.python }}

    - name: Install test dependencies
      run: make test-install

    - name: Make Test
      run: make test
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUNBUFFERED: "1"

    - name: Upload Coverage
      if: always()
      id: upload-coverage
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
      with:
        name: coverage-${{ matrix.python }}
        path: htmlcov/
        if-no-files-found: error
        retention-days: 3
        overwrite: true
        compression-level: 6
